version: '3.8'

services:
  app:
    build: .
    container_name: racoon_app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - MONGO_URI=mongodb://mongo:27017/e-commerce-racoon
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: racoon_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: racoon_redis
    ports:
      - "6379:6379"

volumes:
  mongo-data: